export const belts = [
	{label: 'White belt, no stripes', value: 'white.0'},
	{label: 'White belt, 1 stripe', value: 'white.1'},
	{label: 'White belt, 2 stripes', value: 'white.2'},
	{label: 'White belt, 3 stripes', value: 'white.3'},
	{label: 'White belt, 4 stripes', value: 'white.4'},
	{label: 'Blue belt, no stripes', value: 'blue.0'},
	{label: 'Blue belt, 1 stripe', value: 'blue.1'},
	{label: 'Blue belt, 2 stripes', value: 'blue.2'},
	{label: 'Blue belt, 3 stripes', value: 'blue.3'},
	{label: 'Blue belt, 4 stripes', value: 'blue.4'},
	{label: 'Purple belt, no stripes', value: 'purple.0'},
	{label: 'Purple belt, 1 stripe', value: 'purple.1'},
	{label: 'Purple belt, 2 stripes', value: 'purple.2'},
	{label: 'Purple belt, 3 stripes', value: 'purple.3'},
	{label: 'Purple belt, 4 stripes', value: 'purple.4'},
	{label: 'Brown belt, no stripes', value: 'brown.0'},
	{label: 'Brown belt, 1 stripe', value: 'brown.1'},
	{label: 'Brown belt, 2 stripes', value: 'brown.2'},
	{label: 'Brown belt, 3 stripes', value: 'brown.3'},
	{label: 'Brown belt, 4 stripes', value: 'brown.4'},
	{label: 'Black belt, no stripes', value: 'black.0'},
	{label: 'Black belt, 1 stripe', value: 'black.1'},
	{label: 'Black belt, 2 stripes', value: 'black.2'},
	{label: 'Black belt, 3 stripes', value: 'black.3'},
	{label: 'Black belt, 4 stripes', value: 'black.4'},
]
